version: '3.8'
services:
  acms-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: potgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: acms
    networks:
      - freecodecamp
networks:
  freecodecamp: